# Generated by Django 5.0 on 2024-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('description', models.CharField(default=None, max_length=500)),
                ('price', models.FloatField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
