# Generated by Django 5.0 on 2024-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_photo/'),
        ),
    ]
