# Generated by Django 5.0 on 2024-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookstore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='book_photo/'),
        ),
    ]
