# Generated by Django 5.0 on 2024-01-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookimage',
        ),
    ]
