# Generated by Django 5.0 on 2024-01-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
